version: '3.8'

#Create network 
networks:
  izpbx:
    driver: bridge
  ## if you want run other izpbx deploy in the same docker host enable the macvlan interface driver
  izpbx-ext:
    #driver: macvlan
    driver: bridge
    #driver_opts:
    #  parent: eth0
    ipam:
      driver: default
      config:
         - subnet: 172.18.0.0/29

services:
#DB store data izPBX
  db:
    image: mariadb:10.6.7
    container_name: db
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: unless-stopped
    hostname: db
    env_file:
     - .env
    environment:
     - TZ
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./data/db:/var/lib/mysql
    ## NOTE: to avoid nat management use: 'network_mode: host'
    #network_mode: host
    ## WARNING: if 'network_mode: host' is disabled, comment out the following lines
    networks:
       izpbx-ext:
    ports:
      - ${APP_PORT_MYSQL}:3306

#Records call 
  rhvoice:
    container_name: rhvoice
    build: 
      context: ./rhvoice
      Dockerfile: ./Dockerfile.amd64
    restart: always
    ports:
      - 7080:8080
    networks:
        izpbx-ext:

#Postman is an API platform for developers to design, build, test and iterate their APIs
  postman:
     container_name: restful_booker_checks
     build: 
       context: ./postman-docker
       Dockerfile: ./Dockerfile.postman
     command:
        run Restful_Booker_Collection.json 
        -e environments/Restful_Booker_Environment.json 
        -r html,cli 
        --reporter-html-export reports/Restful_Booker_Test_Run.html
        --reporter-html-template reports/templates/customTemplate.hb
     ports:
        - 7000:8082
     volumes:
        - ./postman/docker/src:/etc/newman
     networks:
         izpbx-ext:

#Build is izPBX
  izpbx:
    build:
      context: ./izpbx-asterisk
      dockerfile: Dockerfile
    container_name: izpbx
    restart: always
    hostname: izpbx
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/izpbx:/data
      - ./nginx/log/:/var/log/httpd/
    ## fail2ban need privileged mode to manage iptables
    #environment:
    # DB_HOST: 127.0.0.1
    cap_add:
      - NET_ADMIN
    privileged: true
    ## NOTE: to avoid SIP-RTP NAT issues use: 'network_mode: host'
    #network_mode: host
    ## WARNING: if 'network_mode: host' is disabled, comment out the following lines
    ##          ports are not needed if using 'network_mode: host' or macvlan network driver
    ##          if you want use macvlan network driver comment out 'izpbx-ext:' too and change exposed IP according your needs
    networks:
         izpbx-ext:
    ports:
     - ${APP_PORT_HTTP}:${APP_PORT_HTTP}
     - ${APP_PORT_LARAVEL}:${APP_PORT_LARAVEL}
    #- ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
    #- ${APP_PORT_IAX}:${APP_PORT_IAX}
    #- ${APP_PORT_IAX}:${APP_PORT_IAX}/udp
     - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}
     - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
     - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
     - ${APP_PORT_SIP}:${APP_PORT_SIP}
    #- ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:10000-20000/udp
    #- ${APP_PORT_WEBRTC}:${APP_PORT_WEBRTC}
    #- ${APP_PORT_UCP_HTTP}:${APP_PORT_UCP_HTTP}
    #- ${APP_PORT_UCP_HTTPS}:${APP_PORT_UCP_HTTPS}
    #- ${APP_PORT_AMI}:${APP_PORT_AMI}
    #- ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}
    #- ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
    #- ${APP_PORT_DHCP}:${APP_PORT_DHCP
