FROM node:16-alpine

#RUN npm install -g newman newman-reporter-html
#WORKDIR /etc/newman

WORKDIR /usr/src/app

COPY package*.json ./

RUN mkdir app/

#ENTRYPOINT ["newman"]

RUN npm install

COPY . .

EXPOSE 8082

CMD [ "node", "server.js" ]